import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./assets/css/fonticon.css";
import "./globals.css";
import "./assets/css/style.css";
import "./assets/css/ressponsive.css";
import HeaderMenu from "@/components/HeaderMenu";
import Footer from "@/components/Footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "XpressMiles",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <HeaderMenu></HeaderMenu>
        {children}
        <Footer></Footer>
        </body>
    </html>
  );
}
